### ISSUE TITLE
Request: 1 or more color changes as time approaches zero

### ISSUE THREAD

**Issue by AndydeCleyre** [Zren/plasma-applet-systraytimer#5]
This is great applet, thank you.

Since it's the same color as all the other systray items, I wish it could gain more visibility as the time decreases (or is short to begin with).

Custom colors, custom time thresholds, and up to at least 3 such thresholds would be ideal, but even fixed colors and a single fixed threshold would still be helpful and worthwhile.

I would probably keep it configured with 3 thresholds something like:

```yaml
- remaining: <= 600s
  color: blue
- remaining: <= 300s
  color: orange
- remaining: <= 60s
  color: red
```
